ClinicManagement/ClinicManagement/Controllers/Api/PatientsController.cs
using AutoMapper;
using ClinicManagement.Core;
using ClinicManagement.Core.Dto;
using ClinicManagement.Core.Models;
using System.Linq;
using System.Web.Http;

namespace ClinicManagement.Controllers.Api
{
    public class PatientsController : ApiController
    {
        private readonly IUnitOfWork _unitOfWork;
        public PatientsController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;

        }

        public IHttpActionResult GetPatients()
        {
            var patientsQuery = _unitOfWork.Patients.GetPatients();


            var patientDto = patientsQuery.ToList()
                                          .Select(Mapper.Map<Patient, PatientDto>);

            return Ok(patientDto);

        }


        [HttpDelete]
        public IHttpActionResult Delete(int id)
        {
            var patient = _unitOfWork.Patients.GetPatient(id);
            _unitOfWork.Patients.Remove(patient);
            _unitOfWork.Complete();
            return Ok();
        }

    }
}

ClinicManagement/ClinicManagement/Controllers/AppointmentsController.cs
using System.Linq;
using System.Web.Mvc;
using ClinicManagement.Core;
using ClinicManagement.Core.Models;
using ClinicManagement.Core.ViewModel;

namespace ClinicManagement.Controllers
{
    public class AppointmentsController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public AppointmentsController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public ActionResult Index()
        {
            var appointments = _unitOfWork.Appointments.GetAppointments();
            return View(appointments);
        }

        public ActionResult Details(int id)
        {
            var appointment = _unitOfWork.Appointments.GetAppointmentWithPatient(id);
            return View("_AppointmentPartial", appointment);
        }
        //public ActionResult Patients(int id)
        //{
        //    var viewModel = new DoctorDetailViewModel()
        //    {
        //        Appointments = _unitOfWork.Appointments.GetAppointmentByDoctor(id),
        //    };
        //    //var upcomingAppnts = _unitOfWork.Appointments.GetAppointmentByDoctor(id);
        //    return View(viewModel);
        //}

        public ActionResult Create(int id)
        {
            var viewModel = new AppointmentFormViewModel
            {
                Patient = id,
                Doctors = _unitOfWork.Doctors.GetAvailableDoctors(),

                Heading = "New Appointment"
            };
            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(AppointmentFormViewModel viewModel)
        {
            if (!ModelState.IsValid)
            {
                viewModel.Doctors = _unitOfWork.Doctors.GetAvailableDoctors();
                return View(viewModel);

            }
            var appointment = new Appointment()
            {
                StartDateTime = viewModel.GetStartDateTime(),
                Detail = viewModel.Detail,
                Status = false,
                PatientId = viewModel.Patient,
                Doctor = _unitOfWork.Doctors.GetDoctor(viewModel.Doctor)

            };
            //Check if the slot is available
            if (_unitOfWork.Appointments.ValidateAppointment(appointment.StartDateTime, viewModel.Doctor))
                return View("InvalidAppointment");

            _unitOfWork.Appointments.Add(appointment);
            _unitOfWork.Complete();
            return RedirectToAction("Index", "Appointments");
        }

        public ActionResult Edit(int id)
        {
            var appointment = _unitOfWork.Appointments.GetAppointment(id);
            var viewModel = new AppointmentFormViewModel()
            {
                Heading = "New Appointment",
                Id = appointment.Id,
                Date = appointment.StartDateTime.ToString("dd/MM/yyyy"),
                Time = appointment.StartDateTime.ToString("HH:mm"),
                Detail = appointment.Detail,
                Status = appointment.Status,
                Patient = appointment.PatientId,
                Doctor = appointment.DoctorId,
                //Patients = _unitOfWork.Patients.GetPatients(),
                Doctors = _unitOfWork.Doctors.GetDectors()
            };
            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(AppointmentFormViewModel viewModel)
        {
            if (!ModelState.IsValid)
            {
                viewModel.Doctors = _unitOfWork.Doctors.GetDectors();
                viewModel.Patients = _unitOfWork.Patients.GetPatients();
                return View(viewModel);
            }

            var appointmentInDb = _unitOfWork.Appointments.GetAppointment(viewModel.Id);
            appointmentInDb.Id = viewModel.Id;
            appointmentInDb.StartDateTime = viewModel.GetStartDateTime();
            appointmentInDb.Detail = viewModel.Detail;
            appointmentInDb.Status = viewModel.Status;
            appointmentInDb.PatientId = viewModel.Patient;
            appointmentInDb.DoctorId = viewModel.Doctor;

            _unitOfWork.Complete();
            return RedirectToAction("Index");

        }

        public ActionResult DoctorsList()
        {
            var doctors = _unitOfWork.Doctors.GetAvailableDoctors();
            if (HttpContext.Request.IsAjaxRequest())
                return Json(new SelectList(doctors.ToArray(), "Id", "Name"), JsonRequestBehavior.AllowGet);
            return RedirectToAction("Create");
        }

        public PartialViewResult GetUpcommingAppointments(int id)
        {
            var appointments = _unitOfWork.Appointments.GetTodaysAppointments(id);
            return PartialView(appointments);
        }

    }
}

ClinicManagement/ClinicManagement/Controllers/DoctorsController.cs
using System.Web.Mvc;
using ClinicManagement.Core;
using ClinicManagement.Core.ViewModel;
using Microsoft.AspNet.Identity;

namespace ClinicManagement.Controllers
{
    [Authorize]
    public class DoctorsController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public DoctorsController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public ActionResult Index()
        {
            var doctors = _unitOfWork.Doctors.GetDectors();
            return View(doctors);
        }

        //Details for admin
        public ActionResult Details(int id)
        {
            var viewModel = new DoctorDetailViewModel
            {
                Doctor = _unitOfWork.Doctors.GetDoctor(id),
                UpcomingAppointments = _unitOfWork.Appointments.GetTodaysAppointments(id),
                Appointments = _unitOfWork.Appointments.GetAppointmentByDoctor(id),
            };
            return View(viewModel);
        }

        public ActionResult DoctorProfile()
        {
            var userId = User.Identity.GetUserId();
            var viewModel = new DoctorDetailViewModel
            {
                Doctor = _unitOfWork.Doctors.GetProfile(userId),
                Appointments = _unitOfWork.Appointments.GetUpcommingAppointments(userId),
            };
            return View(viewModel);
        }
        public ActionResult Edit(int id)
        {
            var doctor = _unitOfWork.Doctors.GetDoctor(id);
            if (doctor == null) return HttpNotFound();
            var viewModel = new DoctorFormViewModel()
            {

                Id = doctor.Id,
                Name = doctor.Name,
                Phone = doctor.Phone,
                Address = doctor.Address,
                IsAvailable = doctor.IsAvailable,
                Specialization = doctor.SpecializationId,
                Specializations = _unitOfWork.Specializations.GetSpecializations()

            };
            return View(viewModel);
        }

        [HttpPost]
        public ActionResult Edit(DoctorFormViewModel viewModel)
        {
            if (!ModelState.IsValid)
            {
                viewModel.Specializations = _unitOfWork.Specializations.GetSpecializations();
                return View(viewModel);
            }

            var doctorInDb = _unitOfWork.Doctors.GetDoctor(viewModel.Id);
            doctorInDb.Id = viewModel.Id;
            doctorInDb.Name = viewModel.Name;
            doctorInDb.Phone = viewModel.Phone;
            doctorInDb.Address = viewModel.Address;
            doctorInDb.IsAvailable = viewModel.IsAvailable;
            doctorInDb.SpecializationId = viewModel.Specialization;

            _unitOfWork.Complete();

            return RedirectToAction("Details", new { id = viewModel.Id });
        }


    }

}

ClinicManagement/ClinicManagement/Controllers/PatientsController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using ClinicManagement.Core;
using ClinicManagement.Core.Models;
using ClinicManagement.Core.ViewModel;

namespace ClinicManagement.Controllers
{
    [Authorize(Roles = RoleName.DoctorRoleName + "," + RoleName.AdministratorRoleName)]
    public class PatientsController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public PatientsController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public ActionResult Index()
        {
            return View();
        }


        public ActionResult Details(int id)
        {
            var viewModel = new PatientDetailViewModel()
            {
                Patient = _unitOfWork.Patients.GetPatient(id),
                Appointments = _unitOfWork.Appointments.GetAppointmentWithPatient(id),
                Attendances = _unitOfWork.Attandences.GetAttendance(id),
                CountAppointments = _unitOfWork.Appointments.CountAppointments(id),
                CountAttendance = _unitOfWork.Attandences.CountAttendances(id)
            };
            return View("Details", viewModel);
        }




        [Authorize]
        public ActionResult Create()
        {
            var viewModel = new PatientFormViewModel
            {
                Cities = _unitOfWork.Cities.GetCities(),
                Heading = "New Patient"
            };
            return View("PatientForm", viewModel);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(PatientFormViewModel viewModel)
        {
            if (!ModelState.IsValid)
            {
                viewModel.Cities = _unitOfWork.Cities.GetCities();
                return View("PatientForm", viewModel);

            }

            var patient = new Patient
            {
                Name = viewModel.Name,
                Phone = viewModel.Phone,
                Address = viewModel.Address,
                DateTime = DateTime.Now,
                BirthDate = viewModel.GetBirthDate(),
                Height = viewModel.Height,
                Weight = viewModel.Weight,
                CityId = viewModel.City,
                Sex = viewModel.Sex,
                Token = (2018 + _unitOfWork.Patients.GetPatients().Count()).ToString().PadLeft(7, '0')
            };

            _unitOfWork.Patients.Add(patient);
            _unitOfWork.Complete();
            return RedirectToAction("Index", "Patients");

            // TODO: BUG redirect to detail 
            //return RedirectToAction("Details", new { id = viewModel.Id });
        }


        public ActionResult Edit(int id)
        {
            var patient = _unitOfWork.Patients.GetPatient(id);

            var viewModel = new PatientFormViewModel
            {
                Heading = "Edit Patient",
                Id = patient.Id,
                Name = patient.Name,
                Phone = patient.Phone,
                Date = patient.DateTime,
                //Date = patient.DateTime.ToString("d MMM yyyy"),
                BirthDate = patient.BirthDate.ToString("dd/MM/yyyy"),
                Address = patient.Address,
                Height = patient.Height,
                Weight = patient.Weight,
                Sex = patient.Sex,
                City = patient.CityId,
                Cities = _unitOfWork.Cities.GetCities()
            };
            return View("PatientForm", viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Update(PatientFormViewModel viewModel)
        {
            if (!ModelState.IsValid)
            {
                viewModel.Cities = _unitOfWork.Cities.GetCities();
                return View("PatientForm", viewModel);
            }


            var patientInDb = _unitOfWork.Patients.GetPatient(viewModel.Id);
            patientInDb.Id = viewModel.Id;
            patientInDb.Name = viewModel.Name;
            patientInDb.Phone = viewModel.Phone;
            patientInDb.BirthDate = viewModel.GetBirthDate();
            patientInDb.Address = viewModel.Address;
            patientInDb.Height = viewModel.Height;
            patientInDb.Weight = viewModel.Weight;
            patientInDb.Sex = viewModel.Sex;
            patientInDb.CityId = viewModel.City;

            _unitOfWork.Complete();
            return RedirectToAction("Index", "Patients")
;
        }



    }
}

ClinicManagement/ClinicManagement/Controllers/ReportsController.cs
using System;
using System.Web.Mvc;
using ClinicManagement.Core;
using ClinicManagement.Core.ViewModel;

namespace ClinicManagement.Controllers
{
    public class ReportsController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public ReportsController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        //======================Attandance ========================//
        public ActionResult Attandences()
        {
            var attandences = _unitOfWork.Attandences.GetAttandences();
            return View(attandences);
        }
        public ActionResult PatientAttandence(string token = null)
        {
            var patientAttandences = _unitOfWork.Attandences.GetPatientAttandences(token);
            return View("_AttandencePartial", patientAttandences);
        }

        // ===============Appointment ========================//
        public ActionResult Appointments()
        {
            var appointments = _unitOfWork.Appointments.GetAppointments();
            return View(appointments);
        }

        [HttpPost]
        public ActionResult Appointments(AppointmentSearchVM viewModel)
        {
            var filter = _unitOfWork.Appointments.FilterAppointments(viewModel);
            return View(filter);
        }
        public ActionResult TestAppointment(AppointmentSearchVM viewModel)
        {
            var filter = _unitOfWork.Appointments.FilterAppointments(viewModel);
            return PartialView("_Appointments", filter);
        }
        //===============End Appointment===================//

        //====================Daily appointment==============//

        public ActionResult DaillyAppointments()
        {
            var daily = _unitOfWork.Appointments.GetAppointments();
            return View(daily);
        }

        public ActionResult Dailly(DateTime getDate)
        {
            var dailyAppointments = _unitOfWork.Appointments.GetDaillyAppointments(getDate);
            return View("_DailyAppointments", dailyAppointments);
        }
    }
}

ClinicManagement/ClinicManagement/Views/Shared/Patients.cshtml
@model ClinicManagement.Core.ViewModel.DoctorDetailViewModel
@{
    ViewBag.Title = "Patients";
    Layout = "~/Views/Shared/_LayoutOut.cshtml";
}
<div class="col-md-12 col-sm-12 col-xs-12">
    <div class="x_panel modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span>
            </button>
            <h4 class="modal-title">Patients</h4>
        </div>

        <div class="x_content modal-body">
            <table id="patients" class="table table-bordered">
                <thead>
                <tr>
                    <th>Token</th>
                    <th>Name</th>
                    <th>Phone</th>
                    <th>Date</th>
                    <th>Time</th>
                    <th>Details</th>
                </tr>

                </thead>
                <tbody>
                @foreach (var item in Model.Appointments)
                {
                    <tr>
                        <td>@item.Patient.Token</td>
                        <td>@item.Patient.Name</td>
                        <td>@item.Patient.Phone</td>
                        <td>@item.StartDateTime.ToString("MMM")-@item.StartDateTime.ToString("d ")-@item.StartDateTime.ToString("yyyy")</td>
                        <td>@item.StartDateTime.ToString("HH:mm")</td>
                        <td>@item.Detail</td>
                        @*<td><a href="@Url.Action("Create","OpdAttendances", new {id = item.Patient.Id})" class="btn-info btn-sm" ><i class="fa fa-plus"></i>OPD</a></td>*@
                    </tr>
                }
                </tbody>
            </table>
        </div>
        <div class="modal-footer">
            <div class="row">
                <div class="col-xs-12">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>

    </div>

</div>

@section scripts{
<script>
    $(document).ready(function() {
        $("#patients").DataTable({
            "scrollY": "300px",
            "scrollCollapse": true,
            "paging": false,
            "filter": false,
            "info": false

        });
    });
        //$('.dataTables').DataTable({
        //    "scrollY": "300px",
        //    "scrollCollapse": true,
        //    "paging": false,
        //    "filter": false,
        //    "info": false
        //});

</script>
}

ClinicManagement/ClinicManagement/Views/Shared/_AdminNav.cshtml
<ul class="nav side-menu">
    <li>
        <a href="/"><i class="fa fa-home"></i> Dashboard </a>
    </li>
    <li><a href="@Url.Action("Index","Patients")"><i class="fa fa-edit"></i> Patient</a></li>
    <li><a href="@Url.Action("Index","Appointments")"><i class="fa fa-edit"></i> Appointment</a></li>
    <li><a href="@Url.Action("Index","Doctors")"><i class="fa fa-edit"></i> Doctors</a></li>
    <li> <a href="@Url.Action("Index","Account")"><i class="fa fa-edit"></i> Users </a> </li>

    <li>
        <a><i class="fa fa-bar-chart-o"></i> Report <span class="fa fa-chevron-down"></span></a>
        <ul class="nav child_menu">
            <li><a href="@Url.Action("DaillyAppointments","Reports")">Dailly Appointments </a></li>
            <li><a href="@Url.Action("Appointments","Reports")">Appointments </a></li>
            <li><a href="@Url.Action("Attandences","Reports")">Attandence </a></li>

        </ul>
    </li>
</ul>

ClinicManagement/ClinicManagement/Views/Shared/_Appointments.cshtml
@model IEnumerable<ClinicManagement.Core.Models.Appointment>
@{
    Layout = null;
}
<div class="col-md-12">
    <div class="x_panel">

        <div class="x_content">
            <table id="appointments" class="table table-striped table-bordered dataTable">
                <thead>
                    <tr>
                        <th>Token</th>
                        <th>Patient name</th>
                        <th>Phone</th>
                        <th>Date</th>
                        <th>Time</th>
                        <th>Doctor</th>
                        <th>Detail</th>
                        <th>Status</th>
                    </tr>

                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.Patient.Token</td>
                            <td>@item.Patient.Name</td>
                            <td>@item.Patient.Phone</td>
                            <td>@item.StartDateTime.ToString("MMM")-@item.StartDateTime.ToString("d ")-@item.StartDateTime.ToString("yyyy")</td>
                            <td>@item.StartDateTime.ToString("HH:mm")</td>
                            <td>@item.Doctor.Name</td>
                            <td>@item.Detail</td>
                            <td>
                                @{
                                if (item.Status == true)
                                {
                                    <a href="#" style="padding: 3px 10px 3px 10px; background-color:green " class="badge" readonly>Approved</a>
                                }
                                else
                                {
                                    <a href="#" style="padding: 3px 10px 3px 10px; background-color:greenyellow " class="badge" readonly>Pending</a>
                                }
                            }
                        </td>
                    </tr>
                                }
                </tbody>
            </table>
        </div>
    </div>

</div>
<script>
    $(document).ready(function () {
        $('.dataTable').DataTable({
            "scrollY": "300px",
            "scrollCollapse": true,
            "paging": false,
            "filter": false,
            "info": false,
            dom: 'Bfrtip',
            buttons: [
                'copy', 'csv', 'excel', 'pdf', 'print'
            ]
        });
    });
</script>

ClinicManagement/ClinicManagement/Views/Shared/_AttandencePartial.cshtml
@model IEnumerable<ClinicManagement.Core.Models.Attendance>
@{
    ViewBag.Title = "Patients";
    Layout = null;
}

<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_content">
                <table class="data table table-striped no-margin dataTable">
                    <thead>
                        <tr>
                            <th>Clinic Remarks</th>
                            <th>Diagnosis</th>
                            <th>Second Diagnosis</th>
                            <th>Third Diagnosis</th>
                            <th>Therapy</th>
                            <th>Date</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>@item.ClinicRemarks</td>
                                <td>@item.Diagnosis</td>
                                <td>@item.SecondDiagnosis</td>
                                <td>@item.ThirdDiagnosis</td>
                                <td>@item.Therapy</td>
                                <td>@item.Date.ToString("MMM"), @item.Date.ToString("d ")-@item.Date.ToString("yyyy")</td>
                            </tr>

                        }
                    </tbody>
                </table>


            </div>
        </div>
    </div>
</div>

<script>
    $(document).ready(function () {
        $('.dataTable').DataTable({
            "scrollY": "300px",
            "scrollCollapse": true,
            "paging": false,
            "filter": false,
            "info": false,
            dom: 'Bfrtip',
            buttons: [
                'copy', 'csv', 'excel', 'pdf', 'print'
            ]
        });
    });
</script>

ClinicManagement/ClinicManagement/Views/Shared/_DailyAppointments.cshtml
@model IEnumerable<ClinicManagement.Core.Models.Appointment>
@{
    
    Layout = null;
}

<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_content">
                <table class=" data table table-striped no-margin dataTable">
                    <thead>
                        <tr>
                            <th>Token</th>
                            <th>Patient name</th>
                            <th>Phone</th>
                            <th>Date</th>
                            <th>Time</th>
                            <th>Doctor</th>
                            <th>Detail</th>
                            <th>Status</th>
                        </tr>

                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>@item.Patient.Token</td>
                                <td>@item.Patient.Name</td>
                                <td>@item.Patient.Phone</td>
                                <td>@item.StartDateTime.ToString("MMM")-@item.StartDateTime.ToString("d ")-@item.StartDateTime.ToString("yyyy")</td>
                                <td>@item.StartDateTime.ToString("HH:mm")</td>
                                <td>@item.Doctor.Name</td>
                                <td>@item.Detail</td>
                                <td>
                                    @{
                                    if (item.Status == true)
                                    {
                                        <a href="#" style="padding: 3px 10px 3px 10px; background-color:green " class="badge" readonly>Approved</a>
                                    }
                                    else
                                    {
                                        <a href="#" style="padding: 3px 10px 3px 10px; background-color:greenyellow" class="badge" readonly>Pending</a>
                                    }
                                }
                            </td>
                        </tr>
                                    }
                    </tbody>
                </table>


            </div>
        </div>
    </div>
</div>
<script>
    $(document).ready(function () {
        $('.dataTable').DataTable({
            "scrollY": "300px",
            "scrollCollapse": true,
            "paging": false,
            "filter": false,
            "info": false,
            dom: 'Bfrtip',
            buttons: [
                'copy', 'csv', 'excel', 'pdf', 'print'
            ]
        });
    });
</script>

ClinicManagement/ClinicManagement/Views/Shared/_Details.cshtml
@model ClinicManagement.Core.ViewModel.PatientDetailViewModel





<div class="container bg-light">
    <div class="py-5 text-center">
    </div>
    @*<div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>*@

    <div class="row modal-body">
        <div class="col-md-4 order-md-2 mb-4">
            <h4 class="d-flex justify-content-between align-items-center mb-3">
                <span class="text-muted">Patient</span>

            </h4>
            <ul class="list-group mb-3">
                <li class="list-group-item d-flex justify-content-between">
                    <span>Token:</span>
                    <strong>@Model.Patient.Token</strong>
                </li>

                <li class="list-group-item d-flex justify-content-between lh-condensed">
                    <div>
                        <h6 class="my-0"> Name</h6>
                        <small class="text-muted">@Model.Patient.Name</small>
                    </div>
                </li>
                <li class="list-group-item d-flex justify-content-between lh-condensed">
                    <div>
                        <h6 class="my-0">Phone</h6>
                        <small class="text-muted">@Model.Patient.Phone</small>
                    </div>
                </li>
                <li class="list-group-item d-flex justify-content-between lh-condensed">
                    <div>
                        <h6 class="my-0">Date Added</h6>
                        <small class="text-muted">@Model.Patient.DateTime.ToString("MMM"), @Model.Patient.DateTime.ToString("d ")- @Model.Patient.DateTime.ToString("yyyy")-@Model.Patient.DateTime.ToString("HH:mm")</small>
                    </div>
                </li>
                <li class="list-group-item d-flex justify-content-between bg-light">
                    <div class="text-success">
                        <h6 class="my-0">Address</h6>
                        <small>@Model.Patient.Address</small>
                    </div>
                </li>
            </ul>

        </div>
        <div class="col-md-8 order-md-1">
            <h4 class="mb-3">Attendances</h4>
            <div class="row">
                <table  class="table table-bordered table-hover dataTables">
                    <thead>
                        <tr>
                            <th class="col-md-4 mb-2">Clinic Remarks</th>
                            <th class="col-md-4 mb-2">Diagnosis</th>
                            <th class="col-md-4 mb-2">Second Diagnosis</th>
                            <th class="col-md-4 mb-2">Third Diagnosis</th>
                            <th class="col-md-4 mb-2">Therapy</th>
                            <th class="col-md-4 mb-2">Date</th>
                            <th class="col-md-4 mb-2">Doctor</th>
                        </tr>
                    </thead>
                    <tbody>


                        @foreach (var item in Model.OpdAttendances)
                        {
                            <tr>
                                <td>@item.ClinicRemarks</td>
                                <td>@item.Diagnosis</td>
                                <td>@item.SecondDiagnosis</td>
                                <td>@item.ThirdDiagnosis</td>
                                <td>@item.Therapy</td>
                                <td>@item.Date.ToString("d")</td>
                                <td>@Model.Patient.Doctor.Name</td>

                            </tr>


                        }
                    </tbody>

                </table>

            </div>

        </div>

    </div>
    <div class="modal-footer">
        <div class="row ">
            <div class="col-xs-12">
                <a href="@Url.Action("Edit", "Patients", new { id= Model.Patient.Id})" class="btn btn-primary"><i class="fa fa-edit fa-fw"></i>Edit Patient</a>

                <a href="@Url.Action("Create", "OpdAttendances", new { id =Model.Patient.Id})" class="btn btn-primary"><i class="fa fa-edit fa-fw"></i> Add Prescription</a>
                <button type="button" class="btn btn-secondary" data-dismiss="modal"> Close</button>

            </div>
        </div>
    </div>

</div>

<script>

         $('.dataTables').DataTable({
             "scrollY": "300px",
             "scrollCollapse": true,
             "paging": false,
             "filter": false,
             "info": false
         });


</script>

ClinicManagement/ClinicManagement/Views/Shared/_DoctorNav.cshtml
<ul class="nav side-menu">
    <li><a href="/"><i class="fa fa-home"></i> Dashboard </a></li>
    @*<li><a href="@Url.Action("Index", "Patients")"><i class="fa fa-edit"></i>Patients</a></li>*@
    <li> <a href="@Url.Action("DoctorProfile","Doctors")"><i class="fa fa-edit"></i>  Profile </a></li>
</ul>

ClinicManagement/ClinicManagement/Views/Shared/_LayoutOut.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Clinic Management System</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body class="nav-md footer_fixed login" >
<div  role="main">
    <div class="">
        @RenderBody()
    </div>
</div>
<!-- footer content -->
<!-- /footer content -->
@Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)


</body>
</html>